FundingPilotSystem/Areas/SystemConfiguration/Controllers/LocalizationSettingsController.cs
using AutoMapper;
using FundingPilotSystem.Common;
using FundingPilotSystem.Controllers;
using FundingPilotSystem.Services.MasterDataProviderService;
using FundingPilotSystem.Utilities;
using FundingPilotSystem.VM;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Resources;
using System.Web.Mvc;
using System.Xml.Linq;
using Telerik.Web.Mvc;

namespace FundingPilotSystem.Areas.SystemConfiguration.Controllers
{
    /// <summary>
    /// Class used for System Configuration for localization
    /// </summary>
    public class LocalizationSettingsController : BaseController
    {
        #region [Declaration]

        private IMasterDataProviderService _masterDataProviderService;

        #endregion

        #region [Constructor]

        public LocalizationSettingsController()
        {
            this._masterDataProviderService = ServiceReferences.GetMasterProviderServiceClient();
        }

        #endregion

        #region [Action]

        /// <summary>
        /// Change Resource method
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult ChangeResource()
        {
            LoggingFramework.Log4NetLogger.Info("UI: In Areas/SystemConfiguration/LocalizationSettings/ChangeResource");

            LocalizationSettingsVM localizationSettingsVm = new LocalizationSettingsVM();
            var systemModule = _masterDataProviderService.GetSystemModules();

            var mappedValues = Mapper.CreateMap<SystemModuleVM, SelectListItem>()
                                      .ForMember(dest => dest.Value, opt => opt.MapFrom(src => src.Id.ToString(CultureInfo.InvariantCulture)))
                                      .ForMember(dest => dest.Text, opt => opt.MapFrom(src => src.Module));

            localizationSettingsVm.SystemModuleDDL = Mapper.Map<List<SystemModuleVM>, List<SelectListItem>>(systemModule);
            localizationSettingsVm.SystemModuleDDL.Insert(0, new SelectListItem { Text = CustomLocalizationUtility.GetKeyValue("CommonResource", "Select"), Value = "0" });

            localizationSettingsVm.Cultures = CommonUtility.GetCultures();
            localizationSettingsVm.Cultures.Insert(0, new SelectListItem { Text = CustomLocalizationUtility.GetKeyValue("CommonResource", "Select"), Value = "0" });

            return View(localizationSettingsVm);
        }

        /// <summary>
        /// Ajax method to load the data in the grid from the resource file
        /// </summary>
        /// <param name="selectedModule"></param>
        /// <param name="selectedCulture"></param>
        /// <returns></returns>
        [GridAction]
        public ActionResult ListResourceAjax(string selectedCulture, string moduleId)
        {
            LoggingFramework.Log4NetLogger.Info(string.Format("{0}-{1}-{2}", "UI: In Areas/SystemConfiguration/LocalizationSettings/ListResourceAjax", selectedCulture, moduleId));
            var moduleResourceData = new List<ResourceDataVM>();
            if (!String.IsNullOrEmpty(moduleId) && !String.IsNullOrEmpty(selectedCulture))
            {
                string sResxPath = GetResourceFilePath(moduleId, selectedCulture);
                if (!System.IO.File.Exists(sResxPath))
                {
                    return View(new GridModel(moduleResourceData));
                }
                moduleResourceData = GetResourceData(sResxPath, moduleId, selectedCulture);
            }
            return View(new GridModel(moduleResourceData));
        }

        /// <summary>
        /// Check is resource file exists or not
        /// </summary>
        /// <param name="culture"></param>
        /// <param name="moduleId"></param>
        /// <returns></returns>
        [HttpPost]
        public string CheckIsResourceFileExists(string culture, string moduleId)
        {
            LoggingFramework.Log4NetLogger.Info(string.Format("{0}-{1}-{2}", "UI: In Areas/SystemConfiguration/LocalizationSettings/CheckIsResourceFileExists", culture, moduleId));
            string sResxPath = GetResourceFilePath(moduleId, culture);
            if (!System.IO.File.Exists(sResxPath))
            {
                return "NOTFOUND"; // when file not found 
            }
            else
            {
                return "FOUND"; // when file found 
            }
        }

        /// <summary>
        /// Create a new resource file from a default file
        /// </summary>
        /// <param name="culture"></param>
        /// <param name="moduleId"></param>
        /// <returns></returns>
        [HttpPost]
        public string CreateNewResourceFile(string culture, string moduleId)
        {
            LoggingFramework.Log4NetLogger.Info(string.Format("{0}-{1}-{2}", "UI: In Areas/SystemConfiguration/LocalizationSettings/CreateNewResourceFile", culture, moduleId));
            string defaultResourcePath = GetResourceFilePath(moduleId, CommonUtility.DefaultCulture);
            if (!String.IsNullOrEmpty(defaultResourcePath))
            {
                if (System.IO.File.Exists(defaultResourcePath))
                {
                    XDocument doc = XDocument.Load(defaultResourcePath);
                    string newFileName = defaultResourcePath.Replace(CommonUtility.DefaultCulture, culture);
                    doc.Save(newFileName);
                    return "FC"; // file changed
                }
            }
            return "DFNF"; // default file not found
        }

        /// <summary>
        /// Save the data changed in the grid inline in the resource file back
        /// </summary>
        /// <param name="updatedR esources"></param>
        /// <returns></returns>
        [AcceptVerbs(HttpVerbs.Post)]
        [GridAction]
        public ActionResult SaveResources([Bind(Prefix = "updated")]IEnumerable<ResourceDataVM> updatedResources)
        {
            LoggingFramework.Log4NetLogger.Info(string.Format("{0}-{1}", "UI: In Areas/SystemConfiguration/LocalizationSettings/SaveResources", updatedResources));

            var updatedResource = updatedResources.FirstOrDefault();

            string selectedModule = Convert.ToString(updatedResource.ModuleId);
            string selectedCulture = updatedResource.CultureValue;

            string sResxPath = GetResourceFilePath(selectedModule, selectedCulture);
            Hashtable data = new Hashtable();
            foreach (var resource in updatedResources)
            {
                data.Add(resource.Key, resource.NewValue);
            }
            UpdateResourceFile(data, sResxPath);
            var moduleResourceData = GetResourceData(sResxPath, selectedModule, selectedCulture);
            return View(new GridModel(moduleResourceData));
        }

        #endregion

        #region [Method]

        /// <summary>
        /// Get the resource file path for a module and culture
        /// </summary>
        /// <param name="moduleId"></param>
        /// <param name="selectedCulture"></param>
        /// <returns></returns>
        internal string GetResourceFilePath(string moduleId, string selectedCulture)
        {
            LoggingFramework.Log4NetLogger.Info(string.Format("{0}-{1}-{2}", "UI: In Areas/SystemConfiguration/LocalizationSettings/GetResourceFilePath", moduleId, selectedCulture));
            string defaultResourceFilePath = GetResourceFilePath(moduleId);
            return defaultResourceFilePath.Replace(CommonUtility.DefaultCulture, selectedCulture);
        }

        /// <summary>
        /// Get the module name by moduleId
        /// </summary>
        /// <param name="ModuleId"></param>
        /// <returns></returns>
        internal string GetResourceFilePath(string moduleId)
        {
            LoggingFramework.Log4NetLogger.Info(string.Format("{0}-{1}", "UI: In Areas/SystemConfiguration/LocalizationSettings/GetModuleName", moduleId));
            var _masterDataProviderService = ServiceReferences.GetMasterProviderServiceClient();

            if (CacheManager.SystemModuleVMList == null)
            {
                CacheManager.SystemModuleVMList = _masterDataProviderService.GetSystemModules();
            }

            int intModuleId;
            int.TryParse(moduleId, out intModuleId);

            if (intModuleId > 0)
            {
                var module = CacheManager.SystemModuleVMList.Where(s => s.Id == intModuleId).SingleOrDefault();

                if (module != null)
                {
                    var serverPath = System.Web.HttpContext.Current.Server.MapPath("~\\App_LocalResources\\");
                    return System.IO.Path.Combine(serverPath, module.ResourceFolderName, module.ResourceFileName);
                }
            }
            return string.Empty;
        }

        /// <summary>
        /// get all the values from the resource file 
        /// </summary>
        /// <param name="path"></param>
        /// <param name="moduleId"></param>
        /// <returns></returns>
        internal List<ResourceDataVM> GetResourceData(string path, string moduleId, string selectedCulture)
        {
            LoggingFramework.Log4NetLogger.Info(string.Format("{0}-{1}-{2}-{3}", "UI: In Areas/SystemConfiguration/LocalizationSettings/GetResourceData", path, moduleId, selectedCulture));
            List<ResourceDataVM> resourceData = new List<ResourceDataVM>();
            string selectedCultureResourceFilePath = GetResourceFilePath(moduleId, selectedCulture);
            if (System.IO.File.Exists(path))
            {
                ResXResourceReader reader = new ResXResourceReader(path);
                if (reader != null)
                {
                    IDictionaryEnumerator id = reader.GetEnumerator();
                    foreach (DictionaryEntry d in reader)
                    {
                        resourceData.Add(new ResourceDataVM
                        {

FundingPilotSystem/Controllers/UserAccountController.cs
using FundingPilotSystem.Common;
using FundingPilotSystem.VM;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FundingPilotSystem.Controllers
{
    public class UserAccountController : Controller
    {
        #region Declarations

        public LoginViewModel loginModel { get; set; }

        #endregion
        public ActionResult Login()
        {
            loginModel = new LoginViewModel();
            return View(loginModel);
        }
        [HttpPost]
        public ActionResult Login(LoginViewModel loginModel)
        {
            if (loginModel.Username == "ad@itmcsoft.com" && loginModel.Password == "admin")
            {
                loginModel.Username = "ad@itmcsoft.com";

                CurrentFPApplicationContext.LoggedInUser = new LoggedInUser()
                 {
                     UserId = loginModel.UserId,
                     Password = loginModel.Password,
                     Username = loginModel.Username,
                     IPAddress = System.Web.HttpContext.Current.Request.UserHostAddress,
                 };

                if (HttpContext.Request.QueryString["returnUrl"] != null)
                {
                    string returnUrl = HttpContext.Request.QueryString["returnUrl"].ToString();
                    if (!string.IsNullOrWhiteSpace(returnUrl))
                    {
                        return Redirect(returnUrl);
                    }
                }

                return RedirectToAction("Index", "Home");
            }
            return View(loginModel);
        }

    }
}

FundingPilotSystem/Views/Shared/AlertWindow.cshtml
@model FundingPilotSystem.Common.AlertModel
@{
    Layout = null;
}

<div class="modal fade" id="alertModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">@Model.WindowTitle</h4>
            </div>
            <div class="modal-body">
                <p>@Model.WindowBody</p>
            </div>
            <div class="modal-footer">
                <button type="button" id="btnAlertOk" onclick="return OnOkAlertModal();" class="btn btn-primary">@Model.OkButtonText</button>
                <button type="button" class="btn btn-default" onclick="return OnHideAlertModal();">@Model.CloseButtonText</button>
              
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

FundingPilotSystem/Views/Shared/FPHeader.cshtml
@using FundingPilotSystem.Common
<div class="wrap">
    <div class="navbar">
        <div class="branding">
            <h1>
                <a class="logo" controller="Home" action="Dashboard" href="@Url.Action("Dashboard", "Home")">
                    <img src="~/Contents/Images/Shared/logo.jpg" width="100" height="100" alt="P2P-logo" />
                </a>
            </h1>
        </div>
        <a class="btn btn-navbar hidden-desktop" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>
        <div class="user">
            <p>
                @if (FPApplication.LoggedInUser != null)
                {
                    @FPApplication.LoggedInUser.Username
               }
        </p>
        @Html.ActionLink("SignOut", "SignOut", "UserAccount")
    </div>
    <div class="container">
        <div class="row">
            <div class="span10">
                <ul class="nav nav-pills">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">My Loan Accounts<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Manage</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">System Configuration<b class="caret bottom-up"></b></a>
                        <ul class="dropdown-menu bottom-up pull-right">
                            <li><a href="#">Account Opening Form Management</a></li>
                            <li><a href="#">Manage E-mail Templates</a></li>
                            <li><a href="#">Customize language of particular page</a></li>
                            <li><a href="@Url.Action("Customize", "CustomLocalization", new { @area = "SystemConfiguration" })">CMS Configuration</a></li>
                            <li class="divider"></li>

                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">My Profile<b class="caret bottom-up"></b></a>
                        <ul class="dropdown-menu bottom-up pull-right">
                            <li><a href="#">Change Registered E-mail</a></li>
                            <li><a href="#">Manage Password Complexity Rules</a></li>
                            <li class="divider"></li>

                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">User Management<b class="caret bottom-up"></b></a>
                        <ul class="dropdown-menu bottom-up pull-right">
                            <li><a href="#">Export User Details</a></li>
                            <li><a href="#">Review User's Access Log</a></li>
                            <li><a href="#">List Accounts</a></li>
                            <li><a href="#">Lock/Unlock User</a></li>
                            <li><a href="#">Review partial KYC  (Yellow flag) User</a></li>
                            <li class="divider"></li>

                        </ul>
                    </li>
                </ul>

            </div>
        </div>
    </div>


</div>
</div>

FundingPilotSystem/Views/Shared/MessageRegionPartial.cshtml
@model List<FundingPilotSystem.Common.ModelMessage>
<div id="commonErrorRegion">
    @{if (Model != null)
      {
          if (Model.Where(m => m.Type == FundingPilotSystem.Common.MessageType.Error).Count() > 0)
          {
        <div style="background: none repeat scroll 0 0 lightyellow; border: 1px solid #DADADA; display: block; margin: 10px; padding: 5px 5px 0;">
            <ul style="list-style: disc; margin-left: 25px; color: red;">
                @foreach (var error in Model)
                {
                    <li style="line-height: 25px;">@error.Message</li>  
                }
            </ul>
        </div>
          }
          else if (Model.Where(m => m.Type == FundingPilotSystem.Common.MessageType.Success).Count() > 0)
          {
        <div style="background: none repeat scroll 0 0 lightyellow; border: 1px solid #DADADA; display: block; margin: 10px; padding: 5px 5px 0;">
            <ul style="list-style: disc; margin-left: 25px; color: green;">
                @foreach (var error in Model)
                {
                    <li style="line-height: 25px;">@error.Message</li>  
                }
            </ul>
        </div>
          }
      }    
    }
</div>

FundingPilotSystem/Views/Shared/_LayoutPage.cshtml
@using FundingPilotSystem.Utilities
@using Telerik.Web.Mvc.UI;
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Html.Style("~/Contents/assets/fonts/Font-Awesome/css/font-awesome.min.css")
    @Html.Style("~/Contents/assets/css/vendor/bootstrap.min.css")
    @Html.Style("~/Contents/assets/css/vendor/bootstrap-theme.min.css")
    @Html.Style("~/Contents/assets/css/vendor/custom.css")
    @Html.Style("~/Contents/Styles/Shared/Common.css")
    
    
    @Html.Script("~/Contents/Scripts/Shared/jquery-1.8.1.min.js")
    @Html.Script("~/Contents/Scripts/Shared/jquery-migrate-1.1.1.min.js")
    @Html.Script("~/Contents/assets/js/vendor/modernizr-2.6.2-respond-1.1.0.min.js")
    @Html.Script("~/Contents/assets/js/vendor/bootstrap.min.js")    
    @(Html.Telerik().StyleSheetRegistrar()
                      .DefaultGroup(group => group
                          .Add("telerik.common.css")
                          .Add("telerik.default.css")
                          .Add("telerik.rtl.css")
                          .Compress(true).CacheDurationInDays(10000))
    )

    @RenderSection("Head", false)
</head>
<body>
    <div id="hiddenValues">
        @Html.Hidden("webUrl", System.Configuration.ConfigurationManager.AppSettings["WebUrlPrefix"])
    </div>
    <div class="container-full">
        <header class="fp-header blue" role="banner">
            <!-- class here will not be part of bootstrap -->
            <div class="container fixHeight">
                <!-- CMS placeholder -->
                <div class="row">
                    <!-- CMS - input with divs - row & column classes + content -->
                    Header – banner option –site wideor page individual-CMS
                </div>
            </div>
        </header>
        <header class="black">
            <!-- Logo, menu, etc NOT CMS -->
            <div class="container navigation-bar">
                <div class="row">
                    <!-- System driven / App content input with div - column classes + content -->
                    <!-- Navigation bar -->
                    <div class="navbar navbar-inverse" role="navigation">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand" href="#">Logo</a>
                        </div>
                        <div class="navbar-collapse collapse">
                            <ul class="nav navbar-nav">
                                <li class="active"><a href="#">Accounts</a></li>
                                <li><a href="#">Loans</a></li>
                                <li><a href="#">Bids</a></li>
                                <li><a href="#">Statements</a></li>
                                <li><a href="#">Settings</a></li>
                                <li>
                                    <a href="@Url.Action("Index", "LocalizationSettings", new { area = "Localization" })">LocalizationSettings</a>
                                </li>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <section class="green">
            <!-- One or more sections, etc NOT CMS -->
            <div class="container fixHeight">
                <div class="row">
                    <!-- System driven / App content input with div - column classes + content -->
                    Section – AppContent
                </div>
            </div>
        </section>
        <section class="fp-section blue">
            <!-- class here will not be part of bootstrap -->
            <div class="container fixHeight">
                <!-- CMS placeholder -->
                <!-- CMS - input with divs - row & column classes + content -->
                <div class="row">
                    Section - CMS
                </div>
            </div>
        </section>
        <section class="mainContentBackground">
            <!-- Mixed content - App content and  -->
            <div class="container fixHeight">
                <div class="row">
                    <div class="col-md-9 no-padding">
                        <!-- System driven / App content input with div - column classes + content -->
                        <div class="green main-content-left">
                            @RenderBody()
                        </div>
                    </div>
                    <aside class="fp-aside">
                        <!-- class here will not be part of bootstrap -->
                        <div class="col-md-3 no-padding">
                            <!-- CMS placeholder -->
                            <!-- CMS - input with nested divs - row & column classes + content -->
                            <div class="blue main-content-right">
                                Aside - CMS
                            </div>
                        </div>
                    </aside>
                </div>
            </div>
        </section>
        <footer class="fp-footer blue">
            <!-- class here will not be part of bootstrap -->
            <div class="container fixHeight">
                <!-- CMS placeholder -->
                <!-- CMS - input with divs - row & column classes + content -->
                <div class="row">
                    Footer - CMS
                </div>
            </div>
        </footer>
    </div>

    @Html.Script("~/Contents/Scripts/Shared/jquery.unobtrusive-ajax.min.js")
    @Html.Script("~/Contents/Scripts/Shared/jquery.validate.min.js")
    @Html.Script("~/Contents/Scripts/Shared/jquery.validate.unobtrusive.min.js")
    @Html.Script("~/Contents/Scripts/Shared/CustomDataAnotationValidation.js")
    @Html.Script("~/Contents/Scripts/Shared/Common.js")
    <!-- Generate resource js files -->
    <script src="~/GenerateResourceJson/CommonResource" type="text/javascript"></script>
    <script src="~/GenerateResourceJson/RegistrationProcess" type="text/javascript"></script>
    <script src="~/GenerateResourceJson/SystemConfigurationResources" type="text/javascript"></script>
    <script src="~/GenerateResourceJson/UserAccountManagement" type="text/javascript"></script>

    @Html.Telerik().ScriptRegistrar().jQuery(false)
</body>
</html>

FundingPilotSystem/Views/Shared/_LayoutPageOld.cshtml
@using FundingPilotSystem.Utilities
@using Telerik.Web.Mvc.UI;
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Html.Style("~/Contents/assets/fonts/open-sans-fontfacekit/stylesheet.min.css")
    @Html.Style("~/Contents/assets/fonts/Font-Awesome/css/font-awesome.min.css")
    @Html.Style("~/Contents/assets/Style.css")
    @Html.Style("~/Contents/assets/FontsStyle.min.css")
    @Html.Style("~/Contents/Styles/Shared/Common.css")

    @Html.Script("~/Contents/Scripts/Shared/jquery-1.8.1.min.js")
    @Html.Script("~/Contents/Scripts/Shared/jquery-migrate-1.1.1.min.js")
    @Html.Script("~/Contents/assets/js/vendor/modernizr-2.6.2-respond-1.1.0.min.js")

    @(Html.Telerik().StyleSheetRegistrar()
                      .DefaultGroup(group => group
                          .Add("telerik.common.css")
                          .Add("telerik.default.css")
                          .Add("telerik.rtl.css")
                          .Compress(true).CacheDurationInDays(10000))
    )

    @RenderSection("Head", false)
</head>
<body>
    <header class="header">
        @Html.Partial("FPHeader")
    </header>
    <div class="content">
        <div class="wrap">
            <div class="sidebar">

            </div>
            <div class="main-content">
                @RenderBody()
            </div>
            @*<div class="sidebarRight">

                </div>*@
        </div>
        <!-- wrap -->
    </div>
    @Html.Script("~/Contents/Scripts/Shared/jquery.unobtrusive-ajax.min.js")
    @Html.Script("~/Contents/Scripts/Shared/jquery.validate.min.js")
    @Html.Script("~/Contents/Scripts/Shared/jquery.validate.unobtrusive.min.js")
    @Html.Script("~/Contents/assets/js/vendor/bootstrap.min.js")


    @Html.Telerik().ScriptRegistrar().jQuery(false)
    @Html.Script("~/Contents/Scripts/Shared/jquery.numeric.validation.min.js")
</body>
</html>